---
# tasks file for get_file_from_ass
#  - name: test - get hostname
#    command:
#      cmd: hostname
#    register: result
#    delegate_to: "{{ast_hostname }}"

#  - name: test - display hostname
#    debug:
#      msg: "{{ result.stdout }}"

  - name: display debug msg
    debug:
      msg: "this is debug message"

  - name: get from as-s to as-t << as-s-(ftp)-acs-(ftp)-as-t >>
    telnet:
      host: "{{ ast_hostname }}" #20.0.1.70
      user: "{{ ast_telnet_user }}"
      password: "{{ ast_telnet_pass }}"
      login_prompt: "ip-20-0-1-70 login: "
      prompts:
        - "[>#]"
      command:
        - hostname
        - echo "this is echo message"
        - cd /var/www/ftp/
        - echo ""                        >  get_file_ansi.sh
        - echo "ftp -n <<END"            >> get_file_ansi.sh
        - echo "open {{ acs_hostname }} {{ acs_port }}" >> get_file_ansi.sh
        - echo "user {{ass_ftp_user}}@{{ ass_hostname }} {{ ass_ftp_pass }}" >> get_file_ansi.sh
        - echo "cd {{ ast_ftp_dir }}"     >> get_file_ansi.sh
        - echo "binary"                   >> get_file_ansi.sh
        - echo "prompt"                   >> get_file_ansi.sh
        - echo "get {{ filename }}"       >> get_file_ansi.sh
        - echo "END"                      >> get_file_ansi.sh
        - bash get_file_ansi.sh
        - cat get_file_ansi.sh
    register: result

  - name: get from as-s to as-t << as-s-(ftp)-as-t >>
    debug:
      msg: "insert task for direct connect here"

  - name: display result
    debug:
      msg: "{{ result.output }}"

  - name: get from ast to target << ast-(ftp)-target >>
    get_url:
      url: "ftp://{{ ast_ftp_user }}:{{ ast_ftp_pass }}@{{ ast_hostname }}/{{ filename }}"
      dest: "{{ dir }}"
    ignore_errors: true


